"""mensaje de lo que cambiaste

Revision ID: 686fd15e336f
Revises: 
Create Date: 2025-09-26 18:58:26.592039

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '686fd15e336f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type_id', sa.String(length=36), nullable=False))
        batch_op.create_foreign_key(None, 'user_type', ['user_type_id'], ['id'])

    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['tipo'])
        batch_op.drop_constraint(batch_op.f('user_type_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.create_foreign_key(batch_op.f('user_type_ibfk_1'), 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_type_id')

    # ### end Alembic commands ###
