"""Agregar user_type_id a director_sector

Revision ID: 910f7dbf2e9a
Revises: 9ce961d7a61e
Create Date: 2025-10-02 10:16:26.762410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '910f7dbf2e9a'
down_revision = '9ce961d7a61e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('director_sector', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_type_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'user_type', ['user_type_id'], ['id'])

    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_type_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('director_sector_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('director_sector_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('user_type_ibfk_2'), 'director_sector', ['director_sector_id'], ['id'])

    with op.batch_alter_table('director_sector', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_type_id')

    # ### end Alembic commands ###
