"""Agrega columna user_id a Reclamo

Revision ID: 9ce961d7a61e
Revises: 686fd15e336f
Create Date: 2025-10-01 21:42:38.816687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ce961d7a61e'
down_revision = '686fd15e336f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=36), nullable=False))
        batch_op.drop_constraint(batch_op.f('reclamo_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('vecino_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vecino_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reclamo_ibfk_1'), 'user', ['vecino_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
