"""agregar campo categoria a reclamos

Revision ID: a5f1c2ff360c
Revises: 910f7dbf2e9a
Create Date: 2025-10-24 22:55:51.487034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f1c2ff360c'
down_revision = '910f7dbf2e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamo', schema=None) as batch_op:
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###
