"""agrego categoria y direccion a reclamos

Revision ID: fb00b7270edc
Revises: a5f1c2ff360c
Create Date: 2025-10-24 23:01:22.170756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb00b7270edc'
down_revision = 'a5f1c2ff360c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direccion', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reclamo', schema=None) as batch_op:
        batch_op.drop_column('direccion')

    # ### end Alembic commands ###
